Extended UNATHORISED event with a property
supertokens/supertokens-website pull request #74
Opened 2021-09-01 12:21 UTC by porcellus

## Summary of change

Added an extra property to indicate what caused the UNAUTHORISED event.

## Related issues
- #73 

## Test Plan

This is a backward-compatible change. I couldn't find any automated testing, manually I tested this in an example application making requests with and without sessions and after deleting/altering the saved tokens.

## Documentation changes

This new property will need some extra documentation

## Checklist for important updates
- [x] Changelog has been updated
- [x] `frontendDriverInterfaceSupported.json` file has been updated (if needed)
   - Along with the associated array in `lib/ts/version.ts`
- [x] Changes to the version if needed
   - In `package.json`
   - In `package-lock.json`
   - In `lib/ts/version.ts`
- [x] Had run `npm run build-pretty`
- [x] Had installed and ran the pre-commit hook
- [x] Issue this PR against the latest non released version branch.
   - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
   - If no such branch exists, then create one from the latest released branch.

2021-09-03 12:42 UTC, rishabhpoddar requested changes
For tests:
- You can modify [this one](https://github.com/supertokens/supertokens-website/blob/master/test/axios.test.js#L330) and [this one](https://github.com/supertokens/supertokens-website/blob/master/test/fetch.test.js#L1765) to see if the boolean value in the event is as expected (boolean should be `false` according to me).
- Then for [this test](https://github.com/supertokens/supertokens-website/blob/master/test/fetch.test.js#L1798), [this one](https://github.com/supertokens/supertokens-website/blob/master/test/fetch.test.js#L1854),  [this test](https://github.com/supertokens/supertokens-website/blob/master/test/axios.test.js#L367) and [this test](https://github.com/supertokens/supertokens-website/blob/master/test/axios.test.js#L424), the boolean should be `true`.

2021-09-03 18:43 UTC, porcellus commented
This https://github.com/supertokens/supertokens-website/blob/master/test/fetch.test.js#L1798 test case (and the axios one as well) should have the property as false I think: clearing cookies essentially removes the session.

2021-09-04 14:13 UTC, rishabhpoddar approved these changes

2021-09-04 14:14 UTC, rishabhpoddar commented
These changes look good. You will also need to modify the docs in the relevant places.

2021-09-07 04:34 UTC, merged